#!/usr/bin/env python3
"""
Changelog Generator - AI 自动生成结构化 Changelog
用法: python changelog-gen.py --repo ./my-project --since HEAD~20 --output ./output/
      python changelog-gen.py --repo ./my-project --from v1.0.0 --to v1.2.0
"""
import os, sys, json, re, argparse, subprocess
from datetime import datetime
from pathlib import Path
from collections import defaultdict

# === Config ===
API_KEY = os.environ.get("CHANGELOG_API_KEY", os.environ.get("OPENAI_API_KEY", ""))
BASE_URL = os.environ.get("CHANGELOG_BASE_URL", os.environ.get("DEEPSEEK_BASE_URL", "https://open.bigmodel.cn/api/paas/v4"))
MODEL = os.environ.get("CHANGELOG_MODEL", "glm-4-flash")
USE_API = bool(API_KEY)

# === Category keywords ===
CATEGORY_RULES = {
    "feat":     ["feat", "add", "新增", "添加", "支持", "implement", "create", "introduce"],
    "fix":      ["fix", "bug", "patch", "修复", "hotfix", "resolve", "correct"],
    "refactor": ["refactor", "rewrite", "重构", "restructure", "migrate", "rename"],
    "docs":     ["docs", "doc", "文档", "readme", "comment", "typo"],
    "perf":     ["perf", "optim", "性能", "加速", "faster", "speed"],
    "test":     ["test", "spec", "测试", "coverage", "mock"],
    "chore":    ["chore", "build", "ci", "deploy", "config", "version", "bump", "release", "clean"],
    "style":    ["style", "format", "lint", "美化", "格式"],
}

def classify_commit(subject):
    """Rule-based commit classification"""
    s = subject.lower().strip()
    # Check conventional commit prefix first: feat(scope): xxx
    m = re.match(r'^(\w+)(\([^)]*\))?:', s)
    if m:
        prefix = m.group(1)
        for cat, keywords in CATEGORY_RULES.items():
            if prefix in keywords or prefix == cat:
                return cat
    # Fallback: keyword match
    for cat, keywords in CATEGORY_RULES.items():
        for kw in keywords:
            if kw in s:
                return cat
    return "other"

def get_commits(repo_path, since=None, to_tag=None):
    """Get commits from git log"""
    cmd = ["git", "-C", repo_path, "log", "--pretty=format:%h|%s|%an|%ad", "--date=short"]
    if since:
        if since.startswith("HEAD~"):
            cmd.extend(["-n", since.replace("HEAD~", "")])
        elif since.startswith("v") or since[0:1].isalpha():
            # tag range
            if to_tag:
                cmd.append(f"{since}..{to_tag}")
            else:
                cmd.append(f"{since}..HEAD")
        else:
            cmd.append(f"--since={since}")
    else:
        cmd.extend(["-n", "50"])

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=10)
        if result.returncode != 0:
            print(f"⚠️ git log failed: {result.stderr.strip()}", file=sys.stderr)
            return []
    except Exception as e:
        print(f"⚠️ git log error: {e}", file=sys.stderr)
        return []

    commits = []
    for line in result.stdout.strip().split("\n"):
        if not line.strip() or "|" not in line:
            continue
        parts = line.split("|", 3)
        if len(parts) < 4:
            continue
        hash_, subject, author, date = parts
        commits.append({
            "hash": hash_.strip(),
            "subject": subject.strip(),
            "author": author.strip(),
            "date": date.strip(),
            "category": classify_commit(subject),
        })
    return commits

def group_by_date(commits):
    """Group commits by date"""
    groups = defaultdict(list)
    for c in commits:
        groups[c["date"]].append(c)
    return dict(sorted(groups.items(), reverse=True))

def group_by_category(commits):
    """Group commits by category"""
    groups = defaultdict(list)
    for c in commits:
        groups[c["category"]].append(c)
    # Sort by frequency
    return dict(sorted(groups.items(), key=lambda x: -len(x[1])))

def render_markdown(commits, repo_name, version="Unreleased"):
    """Render structured changelog to Markdown"""
    lines = []
    lines.append(f"# Changelog")
    lines.append("")
    lines.append(f"## {version} ({datetime.now().strftime('%Y-%m-%d')})")
    lines.append("")

    by_cat = group_by_category(commits)
    cat_labels = {
        "feat": "✨ New Features",
        "fix": "🐛 Bug Fixes",
        "refactor": "♻️ Refactoring",
        "perf": "⚡ Performance",
        "docs": "📝 Documentation",
        "test": "🧪 Tests",
        "chore": "🔧 Maintenance",
        "style": "💄 Style",
        "other": "📦 Other Changes",
    }

    for cat, items in by_cat.items():
        label = cat_labels.get(cat, cat)
        lines.append(f"### {label}")
        for c in items:
            lines.append(f"- {c['subject']} ({c['hash']})")
        lines.append("")

    lines.append("---")
    lines.append(f"> Generated by changelog-gen.py · {len(commits)} commits from **{repo_name}**")

    return "\n".join(lines)

def generate_with_api(commits, repo_name, version):
    """Call LLM for enhanced changelog"""
    import urllib.request

    # Build structured input (NOT raw text)
    commit_data = []
    for c in commits:
        commit_data.append(f"[{c['category']}] {c['hash']} {c['subject']} ({c['author']}, {c['date']})")

    prompt = f"""你是一位专业的开源项目维护者，请根据以下 commit 记录生成一份结构化的 Changelog。

# 严格要求
1. **只使用下方提供的 commit 数据，禁止编造任何内容**
2. 按类别分组：Features / Fixes / Improvements / Other
3. 每条用简洁的语言重写（不要照搬 commit message）
4. 中文为主，技术术语保留英文
5. 开头写一段 2-3 句的版本摘要

# 输出格式
```
# Changelog

## [{version}] - {datetime.now().strftime('%Y-%m-%d')}

### 摘要
[2-3句版本摘要]

### ✨ New Features
- [描述] ({hash})

### 🐛 Bug Fixes
- [描述] ({hash})

### ♻️ Improvements
- [描述] ({hash})

### 📦 Other
- [描述] ({hash})

---
> Generated by changelog-gen
```

# Commit 数据（共 {len(commits)} 条）
{chr(10).join(commit_data)}
"""

    url = f"{BASE_URL}/chat/completions"
    payload = json.dumps({
        "model": MODEL,
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.5,
        "max_tokens": 2000,
    }).encode()
    req = urllib.request.Request(url, data=payload, headers={
        "Content-Type": "application/json",
        "Authorization": f"Bearer {API_KEY}",
    })
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            result = json.loads(resp.read().decode())
            return result["choices"][0]["message"]["content"]
    except Exception as e:
        print(f"⚠️ API call failed: {e}", file=sys.stderr)
        return None

def main():
    parser = argparse.ArgumentParser(description="AI Changelog Generator")
    parser.add_argument("--repo", required=True, help="Path to git repository")
    parser.add_argument("--since", default="HEAD~30", help="Since: HEAD~N, tag, or date")
    parser.add_argument("--to", default=None, help="To tag (default: HEAD)")
    parser.add_argument("--version", default="Unreleased", help="Version label")
    parser.add_argument("--output", default="./output", help="Output directory")
    parser.add_argument("--no-api", action="store_true", help="Skip API, use template only")
    args = parser.parse_args()

    repo = Path(args.repo).resolve()
    if not (repo / ".git").exists():
        print(f"❌ Not a git repo: {repo}", file=sys.stderr)
        sys.exit(1)

    print(f"📂 Repo: {repo.name}")
    commits = get_commits(str(repo), args.since, args.to)
    if not commits:
        print("❌ No commits found", file=sys.stderr)
        sys.exit(1)

    print(f"📊 Found {len(commits)} commits")

    # Category stats
    by_cat = group_by_category(commits)
    for cat, items in by_cat.items():
        print(f"  {cat}: {len(items)}")

    # Generate
    result = None
    if USE_API and not args.no_api:
        print("🤖 Generating with API...")
        result = generate_with_api(commits, repo.name, args.version)
        if result:
            # Strip markdown code block if present
            result = re.sub(r'^```\n?', '', result)
            result = re.sub(r'\n?```$', '', result)
            print("✅ API generation succeeded")
        else:
            print("⚠️ API failed, falling back to template")

    if not result:
        print("📝 Using template mode")
        result = render_markdown(commits, repo.name, args.version)

    # Save
    out_dir = Path(args.output)
    out_dir.mkdir(parents=True, exist_ok=True)
    filename = f"CHANGELOG-{repo.name}-{args.version}.md"
    out_path = out_dir / filename
    out_path.write_text(result, encoding="utf-8")
    print(f"💾 Saved: {out_path} ({len(result)} chars)")

if __name__ == "__main__":
    main()
